# Generated by Django 5.0 on 2023-12-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0010_alter_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
