# Generated by Django 5.0 on 2023-12-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0012_delete_commentt_remove_comment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
