# Generated by Django 5.0 on 2023-12-13 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0018_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
