# Generated by Django 5.0 on 2023-12-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0019_remove_comment_post_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commenttt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='socialapp.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
