# Generated by Django 5.0 on 2023-12-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0020_commenttt_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenttt',
            old_name='user',
            new_name='user_name',
        ),
    ]
