# Generated by Django 5.0 on 2023-12-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0021_rename_user_commenttt_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenttt',
            old_name='user_name',
            new_name='user',
        ),
    ]
